name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: test
        run: echo "Testing the code..."