name: Build Docker Image

on:
  schedule:
    # Runs every 5 minutes test
    - cron: '*/5 * * * *'
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      IMG_NAME: 'ignition-image'
      IMG_NAME2: 'ignition-image2'
      FOLDER_NAME: 'dockerfiles/ignition'
      FOLDER_NAME2: 'otherdockerfiles/ignition'
      REPO_URL: 'test_url'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: build image
        run: |
          docker build -t $REPO_URL/$IMG_NAME:$GITHUB_SHA -t $REPO_URL/$IMG_NAME:latest ./$FOLDER_NAME
          docker build -t $REPO_URL/$IMG_NAME2:$GITHUB_SHA -t $REPO_URL/$IMG_NAME2:latest ./$FOLDER_NAME2
          docker images
          echo "testing develop"